name: Build and Deploy to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Validate package.json
        run: |
          node -e "const pkg = require('./package.json'); console.log('Package name:', pkg.name); console.log('Package version:', pkg.version)"
          
      - name: Install Dependencies
        run: npm ci --only=production

      - name: Build Project
        run: npm run build --if-present

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: hvms-app-centralin   # your app service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
